### ISSUE TITLE
Ignore file name or path patterns

### ISSUE THREAD

**Issue by alippai** [src-d/hercules#107]
Is it possible, to ignore a file pattern? package-lock.json files for javascript applications are huge

**Comment by vmarkovtsev** [comment]
It is really not obvious from `--help` (my bad) but the following should work: `--skip-blacklist --blacklisted-dirs=path/to/package-lock.json`. If that file is on the root level: `--skip-blacklist --blacklisted-dirs=package-lock.json`

**Comment by alippai** [comment]
I didn't realize there is --help, I'm more used to README.md (where there is no mention). I'm going to play with this all day, good bye productivity :D

**Comment by vmarkovtsev** [comment]
Resolved by https://github.com/src-d/hercules/pull/109
