### ISSUE TITLE
Panic: repository already exists

### ISSUE THREAD

**Issue by marnovo** [src-d/hercules#16]
When you run `hercules` in a remote URL repository after it was already run once (thus it is in the `/tmp/repo-cache` folder, for example), you get a `panic: repository already exists`error message.

Hercules could either download the repository again (which could have been updated, for example) or just skip it since it is already in place (in this case you miss any updates in the remote repo) instead of returning a panic.

P.s.: removing `/tmp/repo-cache` will enable you to run it again as if it was the first time, without the panic.

Log:
```
>>> hercules https://github.com/src-d/go-git /tmp/repo-cache | python3 labours.py --resample raw --output go-git.json
panic: repository already exists

goroutine 1 [running]:
main.main()
	/Users/xxxxxx/go/src/gopkg.in/src-d/hercules.v2/cmd/hercules/main.go:151 +0xad6
Reading the input... Warning: failed to import yaml.CLoader, falling back to slow yaml.Loader
done
Traceback (most recent call last):
  File "labours.py", line 869, in <module>
    sys.exit(main())
  File "labours.py", line 794, in main
    header = reader.get_header()
  File "labours.py", line 119, in get_header
    header = self.data["burndown"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vmarkovtsev** [comment]
All right, looks like the cache feature is not properly covered in the manual.

This is what's happening. The first run stores the repo into `/tmp/repo-cache`. The second run tries to store the repo again but fails because the directory is not empty. What you should instead run is

```
hercules /tmp/repo-cache
```

I will update the readme.

**Comment by vmarkovtsev** [comment]
Fixed in https://github.com/src-d/hercules/commit/733728cae1b9f8f19c727b33da7f69c296f7830c

**Comment by marnovo** [comment]
I'd still say a more appropriate behavior would be _not_ panicking and either using the cache or redownloading the repo (depending on the flag or the user input). However, 733728c already helps with user debugging the eventual error. 👍
