### ISSUE TITLE
slice bounds out of range error

### ISSUE THREAD

**Issue by Gr33nbl00d** [src-d/hercules#163]
What i get after running
`hercules --devs <repo> | python labours.py -m devs`

 2417 / 29722  1h58m45spanic: runtime error: slice bounds out of range

goroutine 4816 [running]:
gopkg.in/src-d/hercules.v6/internal/plumbing.(*RenameAnalysis).blobsAreClose(0xc000a49580, 0xc04aa1e370, 0xc00c8b60a0, 0xc00b80ee48, 0x9, 0xc0933c3f90)
        c:/gopath/src/gopkg.in/src-d/hercules.v6/internal/plumbing/renames.go:411 +0xb30
gopkg.in/src-d/hercules.v6/internal/plumbing.(*RenameAnalysis).Consume.func1(0x0, 0x0)
        c:/gopath/src/gopkg.in/src-d/hercules.v6/internal/plumbing/renames.go:232 +0x41b
gopkg.in/src-d/hercules.v6/internal/plumbing.(*RenameAnalysis).Consume.func3(0xc00b313950, 0xc00650cd30)
        c:/gopath/src/gopkg.in/src-d/hercules.v6/internal/plumbing/renames.go:314 +0x2e
created by gopkg.in/src-d/hercules.v6/internal/plumbing.(*RenameAnalysis).Consume
        c:/gopath/src/gopkg.in/src-d/hercules.v6/internal/plumbing/renames.go:314 +0x1a7b

No data has been read - has Hercules crashed?

**Comment by vmarkovtsev** [comment]
This is clearly a crash @Gr33nbl00d 

Can you send me the repo you analyzed; if it is not possible, I will try to suggest fixes but I will need your assistance to test.

**Comment by Gr33nbl00d** [comment]
Hi no problem it is quite problematic to send you this repo as it is really big 1.7M Lines of Code and also im not allowed as it is confidential. Its is reproducable and crashes always on the same step with the same error. No Problem i will try to help :)

**Comment by vmarkovtsev** [comment]
OK. If you are able to build Hercules, then I can send you a patch which prints the hashes of the two offending compared Git blobs, then you execute `git show <hash>` for each and send me the output (file contents) through email. Does it sound good?

**Comment by vmarkovtsev** [comment]
@Gr33nbl00d Please use the binary from "debug" release, it contains the patch: https://github.com/src-d/hercules/releases/tag/debug

**Comment by Gr33nbl00d** [comment]
thank you i will try

**Comment by vmarkovtsev** [comment]
Good, so now I need you to run
```
git show ecc236816c8bddf3523d39ec0f7650591c829fb6 | gzip > file1.gz
git show 7f06d8f55b010f2daf01d2b50747c2ba2ff11f8d | gzip > file2.gz
```
And send me those two files. My email can be taken from e.g. https://github.com/src-d/hercules/commit/b8fb564c3acd2da61027c9f909a22e33c9c1626b.patch

**Comment by Gr33nbl00d** [comment]
Ok no Problem take your time :) I am glad i could help and looking forward for your fix :)

**Comment by vmarkovtsev** [comment]
@Gr33nbl00d

**Comment by vmarkovtsev** [comment]
Should be fixed in https://github.com/src-d/hercules/releases/tag/v7
