### ISSUE TITLE
Add support for multiple repositories

### ISSUE THREAD

**Issue by engel75** [src-d/hercules#18]
would be great to add the option to analyze multiple repositories and merge the statistics? I would like to analyze http://git.openstack.org.

All the best,
Flo

**Comment by vmarkovtsev** [comment]
Thanks for the suggestion! Indeed, it should be possible. Put on my list.

**Comment by engel75** [comment]
great!

**Comment by vmarkovtsev** [comment]
PRs welcome! 🍺

**Comment by vmarkovtsev** [comment]
Implemented. Please use `hercules-combine`. The build process was changed, now you have to use `make`. The cmdline usage was also changed. README should cover everything.
