### ISSUE TITLE
'go mod' cannot pull dependencies

### ISSUE THREAD

**Issue by bobheadxi** [src-d/hercules#229]
There seems to be a dependency, imported as `github.com/jeffail/tunny`, that declares a `go.mod` file with the module path `github.com/Jeffail/tunny` (capital J). This causes `go mod` to break:

```
❯ go get gopkg.in/src-d/hercules.v9
go: finding github.com/jeffail/tunny latest
go: finding github.com/gogo/protobuf/proto latest
go: finding github.com/gogo/protobuf/sortkeys latest
go: finding github.com/minio/highwayhash latest
go: github.com/jeffail/tunny@v0.0.0-20181108205650-4921fff29480: parsing go.mod: unexpected module path "github.com/Jeffail/tunny"
```

related: https://github.com/golang/go/issues/27154

**Comment by vmarkovtsev** [comment]
Ouch... I haven't used modules in Hercules yet, so this went unnoticed. Does it mean that after merging #230 Hercules will be mod-compatible?

**Comment by bobheadxi** [comment]
It should, though ideally someone would run `go mod init` to migrate over the `Gopkg.lock` resolutions as well

I think a new release needs to be tagged though, for the changes to show up in gopkg.in? I'm not familiar with the specifics of how gopkg.in works

Thanks!

**Comment by vmarkovtsev** [comment]
Pushed v9.1.0

**Comment by bobheadxi** [comment]
It's working with `go mod` now - thanks!
