### ISSUE TITLE
feature: finer granularity options for burndown

### ISSUE THREAD

**Issue by bobheadxi** [src-d/hercules#238]
While on *most* repos, 1 day is about as granular as you'll need, it would be nice to have the option to set granularity to, say, 0.5 days, or even some number of hours, to look at hackathon projects (which typically span just 24-48 hours).

For such short projects (e.g. https://github.com/launchpals/open-now), the burndowns don't present very interesting data (`granularity=1`):

```
  "Global": [
    [ 343,  0,  0 ],
    [ 309, 470371,  0 ],
    [ 309, 470341, 2073 ],
  ],
```

I'm very interesting in implementing this, though it looks like it won't be all too trivial (a lot of the code seems focused around granularity as days). Any pointers would be appreciated!

it seems like this might be related to #134, but I'm not sure what the plans are for that one, and whether or not it's part of `burndown`

**Comment by vmarkovtsev** [comment]
Indeed, the current code is pretty much nailed to days. However, I think that we can hack this by tricking everybody outside of `DaysSinceStart`. It is possible to add a command line argument to that item which changes the time scale. So "one day" for all the rest of the items may equal to 1 hour, 12 hours, etc.
Therefore "day" should be renamed to "tick" everywhere, and its length should be included into yaml/pb output the same way as we currently include the list of people.

Feel free to work on this! PRs are always welcome.

**Comment by vmarkovtsev** [comment]
We can further simplify implementation by requiring the same real one-day tick length while merging Burndown results together (`BurndownAnalysis.MergeResults`).
