### ISSUE TITLE
question: how to remove duplicate color bands in people burndown?

### ISSUE THREAD

**Issue by efx** [src-d/hercules#252]
Thank you for building this tool! 
I noticed for repositories that have numerous contributors, the plot color bands repeat:
Specifically in the ember.js example, the dark orange color repeats for 3 distinct contributors.
https://github.com/src-d/hercules#code-ownership

Is there a way to configure `labours.py` so it will generate bands using distinct colors?

**Comment by vmarkovtsev** [comment]
You can try different `--style` values, but it will not help much, probably. This is a built-in Matplotlib limitation, it repeats the colors once the color scheme is exhausted. Ideally, the plots should be interactive and web-based, but there is no internal HR for that currently. There is also [hercules-web](https://github.com/smacker/hercules-web) by my colleague @smacker
