### ISSUE TITLE
unable to import v10

### ISSUE THREAD

**Issue by bobheadxi** [src-d/hercules#257]
```
❯ go get gopkg.in/src-d/hercules.v10
package gopkg.in/src-d/hercules.v10: unrecognized import path "gopkg.in/src-d/hercules.v10" (parse https://gopkg.in/src-d/hercules.v10?go-get=1: no go-import meta tags ())
```

it doesnt show up on `gopkg` either: https://gopkg.in/src-d/hercules.v9

the `gopkg` documentation implies the tag must begin with a `v`, whereas the version 10 tag is just [`10.0.0`](https://github.com/src-d/hercules/releases/tag/10.0.0) currently:

![image](https://user-images.githubusercontent.com/23356519/54859973-ca276a00-4cd0-11e9-8cde-9e8c72983464.png)

**Comment by vmarkovtsev** [comment]
Yeah, I am debugging the Python package deployment, everything is broken currently, and I have to force push to master because it is the only way to test PyPi Travis deployment.

**Comment by bobheadxi** [comment]
Was able to successfully pull `v10` with the [new tag](https://github.com/src-d/hercules/releases/tag/v10.0.0) - thanks!
