### ISSUE TITLE
Possible reason for "Devs stats were not collected" error

### ISSUE THREAD

**Issue by nitishMehrotra** [src-d/hercules#265]

**Comment by vmarkovtsev** [comment]
The possible reasons vary from high energy particles swapping a single bit in RAM to some secret CIA rootkit interfering with your OS.

**Comment by nitishMehrotra** [comment]
Apologies for not being explicit about the error. I am trying to use hercules on one of our internal code repos and I am getting the error stated above. Its similar to this issue https://github.com/src-d/hercules/issues/190 but with no details about the error. 

Any suggestions on ow to debug this error?

**Comment by vmarkovtsev** [comment]
I believe that this is the problem as in #266. It is fixed in the current master, though a new release will take a few days to make.

**Comment by vmarkovtsev** [comment]
The fix was released in 10.0.1
