### ISSUE TITLE
Ownership plot still shows ownership after files were deleted

### ISSUE THREAD

**Issue by remram44** [src-d/hercules#267]
A significant portion of my ownership plot is taken from contributors whose files I deleted.

To reproduce:
```
hercules --burndown --burndown-people --pb https://github.com/VIDA-NYU/reprozip \
| labours -f pb -m ownership -o ownership.png
```
![ownership.png](https://user-images.githubusercontent.com/426784/55674535-fff95080-5883-11e9-8417-cfb55297f723.png)

All files from Manfred Touron were [deleted in 2015](https://github.com/ViDA-NYU/reprozip/commit/68cda790e3f91057b3293df6524ca3533dd4548e), but there is no change in the plot.

**Comment by vmarkovtsev** [comment]
Thanks, I will have a look. Most likely, there is an undeleted branch which still has those files.

**Comment by vmarkovtsev** [comment]
The files from the pointed commit are actually correctly removed from the stats. However, `uml-builder/.config`, which appears in `0752cca7abfd1d625db756d0fc7d4e9b881536e0`, gets removed during the merge `5da973251d3402230a429d09aa827e51072aeba1`. Merge commits are an ownership stats nightmare, investigating further.

**Comment by vmarkovtsev** [comment]
Yes, the core problem is that I am incorrectly handling **full file** deletions and insertions during merges. Nice one.

**Comment by remram44** [comment]
Thank you for the quick fix! I have confirmed that this fixes my problem completely.
