### ISSUE TITLE
hercules combine is mismatching timelines

### ISSUE THREAD

**Issue by jrotter** [src-d/hercules#278]
(I'm using the docker container, but will simplify my commands for this example.)  I am creating pb files with the following commands via the hercules docker container:
```
hercules --devs --pb /git/repo1 > repo1.pb
hercules --devs --pb /git/repo1 > repo2.pb
```
Then I use combine as follows:
```
hercules combine repo1.pb | labours -f pb -m devs -o repo1.png
hercules combine repo2.pb | labours -f pb -m devs -o repo2.png
hercules combine repo1.pb repo2.pb | labours -f pb -m devs -o both.png
```
The users in these two repositories are mutually exclusive.

Here's user1 in repo1.png:
![repo1](https://user-images.githubusercontent.com/5429149/56702025-f23f2a00-66cf-11e9-977e-d81259312746.png)

Here's user2 in repo2.png:
![repo2](https://user-images.githubusercontent.com/5429149/56702030-fc612880-66cf-11e9-80fe-8b5ac1839f62.png)

Here are user2 and user1 in both.png:
![both](https://user-images.githubusercontent.com/5429149/56702037-04b96380-66d0-11e9-88ab-7c12e07baa17.png)

Note that the volume for each users is identical, but the timeline for user1 has shifted left to match the start of user2's timeline.

Here's the version info:
```
$ hercules version
Version: 10
Git:     5c9c6c1617842aad70895afdb2d10fb05e189105
```
Is this a bug, or am I missing something in my use of `hercules combine`?

**Comment by vmarkovtsev** [comment]
This is a bug, thanks for reporting. When the series get merged, I miss the time delta. To be fixed this week.

**Comment by jrotter** [comment]
Awesome, thank you!

**Comment by vmarkovtsev** [comment]
Should be fixed in the current master.

**Comment by vmarkovtsev** [comment]
Please ping here if it did not help, I will reopen at once.
