### ISSUE TITLE
[performance] The burndown analysis runs forever on the C++ driver repo

### ISSUE THREAD

**Issue by warenlg** [src-d/hercules#294]
I'm not able to process some driver repos from bblfsh codebase with the following command. Particularly the C++ driver https://github.com/bblfsh/cpp-driver that seems to be a small normal repo but the job runs forever: it has not finished after one night. Other driver repos are fine (less than 1 sec processing) apart from the JS and Go drivers that required 20min.
I used the version `9.2.0` of the executable, locally.
Ubuntu 18.04.2

`./hercules_v9.2.0 --pb --burndown --burndown-people --burndown-files --devs --couples --hibernation-distance=1000 --skip-blacklist path_to_repo`

**Comment by vmarkovtsev** [comment]
Questions:

- 100% CPU or 0% CPU when it hangs?
- bblfshd version?
- C++ driver version?
- Please show relevant (not all!) bblfshd logs.

**Comment by warenlg** [comment]
100% CPU and it hangs on this commit `68d4981`

**Comment by warenlg** [comment]
Same thing here actually,

https://github.com/bblfsh/go-driver/commit/26c8f55eab35de5648bd0a1cf8a663d32cf3c1fe
https://github.com/bblfsh/go-driver/commit/2995529cf147987ee244abef083aca8e915f1fee
https://github.com/bblfsh/javascript-driver/commit/f63272417f57f7d7675f832112ed44c92a1b4a1e

**Comment by vmarkovtsev** [comment]
Root cause: too big text files make diffmatchpatch enter an infinite cycle. I need to add a timeout for diff-ing.
