### ISSUE TITLE
Running couples and shotness through Docker

### ISSUE THREAD

**Issue by scapista** [src-d/hercules#295]
I am attempting to run your shotness and couples flags with varying results.  Maybe I'm misunderstanding the documentation and this is user error. When running shotness i am getting a dependency issue in hercules. 

Example 1:
docker run srcd/hercules hercules --shotness --pb https://github.com/pallets/jinja >test.pb

<img width="976" alt="Screen Shot 2019-07-02 at 3 38 06 AM" src="https://user-images.githubusercontent.com/10610451/60493524-f90f8d80-9c7a-11e9-8136-558653d7315a.png">

When running couples hercules seems to be generating couples output but when i try to pass that to labours im getting an arguments error.  Based on your documentation i would have expected to be able to run labours with the shotness flag but this asks me to run hercules with the shotness flag specifically..

Example 2:
docker run srcd/hercules hercules --couples --pb https://github.com/pallets/jinja >test.pb
labours -m couples -o mitsuhiko -f pb <test.pb

<img width="1280" alt="Screen Shot 2019-07-02 at 3 56 21 AM" src="https://user-images.githubusercontent.com/10610451/60494800-8653e180-9c7d-11e9-8f20-bc2b9193de47.png">

labours -m shotness -f pb <test.pb

<img width="907" alt="Screen Shot 2019-07-02 at 3 49 11 AM" src="https://user-images.githubusercontent.com/10610451/60494325-8dc6bb00-9c7c-11e9-8b91-34ca9998bb55.png">

**Comment by vmarkovtsev** [comment]
Hi @scapista 

Try `hercules --feature uast --shotness`. The feature should be enabled automatically, but since you see an error stack, something got broken. I'll have a look.

Regarding `-m couples`, the error message suggests `couples-files` or `couples-people`. You should try one of those instead.
