### ISSUE TITLE
No output 

### ISSUE THREAD

**Issue by abirhajji** [src-d/hercules#296]
I am running hercules using the following command 

`hercules --couples path/to/repos > output.yml`
I got no data an it doesn't finish the process . 
I have 200G disk , 32 RAM, 8CPU

**Comment by vmarkovtsev** [comment]
Hi @abirhajji 

> `path/to/repos`

repos or repo? Hercules works on a single repository, always, as noted in the readme.

I need the log (progress bar when it "hangs") and the repository to reproduce your problem. Also, is your CPU 200% busy during the "hang" or not?

**Comment by vmarkovtsev** [comment]
@abirhajji ping

**Comment by abirhajji** [comment]
it was CPUs problem I need a machine with more CPUs

**Comment by vmarkovtsev** [comment]
Try the new release, it should probably help.

**Comment by vmarkovtsev** [comment]
ok, closing for now, please write here if the problem persists and I will re-open at once!
