### ISSUE TITLE
Getting error which running sentiment analysis

### ISSUE THREAD

**Issue by buddies2705** [src-d/hercules#300]
I have attached a screenshot of the error.

```
hercules --sentiment --pb https://github.com/bitcoin/bitcoin | labours -m sentiment -f pb
[ERROR] 2019/07/31 17:19:58 Unsatisfied dependency: [uasts] -> UASTChanges
[ERROR] 2019/07/31 17:19:58 stacktrace:
gopkg.in/src-d/hercules.v10/internal/core.(*Pipeline).resolve(0xc0ec423cb8, 0x0, 0x0, 0x10, 0xc0001133d8)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/internal/core/pipeline.go:573 +0x1a2c
gopkg.in/src-d/hercules.v10/internal/core.(*Pipeline).Initialize(0xc0ec423cb8, 0xc000a2d320, 0x0, 0x0)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/internal/core/pipeline.go:689 +0x27c
main.glob..func3(0x33582a0, 0xc000a2d590, 0x1, 0x3)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/cmd/hercules/root.go:266 +0x9bd
gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra.(*Command).execute(0x33582a0, 0xc000032110, 0x3, 0x3, 0x33582a0, 0xc000032110)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x33582a0, 0xc000e9a600, 0xc000eb7f88, 0x8b197f)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/home/batman/go/src/gopkg.in/src-d/hercules.v10/cmd/hercules/root.go:510 +0x32

[ERROR] 2019/07/31 17:19:58 Failed to initialize the pipeline on [https://github.com/bitcoin/bitcoin]
2019/07/31 17:19:58 unsatisfied dependency
Traceback (most recent call last):
  File "/home/batman/.local/bin/labours", line 11, in <module>
    load_entry_point('labours', 'console_scripts', 'labours')()
  File "/home/batman/go/src/gopkg.in/src-d/hercules.v10/python/labours/labours.py", line 1730, in main
    reader = read_input(args)
  File "/home/batman/go/src/gopkg.in/src-d/hercules.v10/python/labours/labours.py", line 409, in read_input
    reader.read(args.input)
  File "/home/batman/go/src/gopkg.in/src-d/hercules.v10/python/labours/labours.py", line 278, in read
    raise ValueError("empty input")
ValueError: empty input
```

![Screenshot from 2019-07-31 17-31-17](https://user-images.githubusercontent.com/6241365/62210241-46396900-b3b9-11e9-8563-0b625da6fb9d.png)

**Comment by vmarkovtsev** [comment]
Thanks for reporting. Can you please add `--feature uast` to `hercules`.

I will fix this properly soon.

**Comment by buddies2705** [comment]
Thanks for the quick response now I am getting this. 

![Screenshot from 2019-07-31 19-00-49](https://user-images.githubusercontent.com/6241365/62215980-8c94c500-b3c5-11e9-88fa-ca489179d67f.png)

**Comment by buddies2705** [comment]
I started Babelfish docker image using below command  

`docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd:latest`

Now getting this

![Screenshot from 2019-07-31 19-09-28](https://user-images.githubusercontent.com/6241365/62216643-c4e8d300-b3c6-11e9-8325-e95d369debfd.png)

**Comment by vmarkovtsev** [comment]
You need to install the drivers:

```
docker exec -i bblfshd bblfshctl driver install --recommended
```

**Comment by buddies2705** [comment]
Thanks, I removed the stateless image and used Embedded drivers image, which worked.

**Comment by buddies2705** [comment]
Also for when using  --commits-stat  with hercules, what should I use with labours?  

 hercules --commit-stat |   labours -m ?

**Comment by vmarkovtsev** [comment]
OK this thread went very far away off the original topic :smile: 

Can you please create separate issues.

**Comment by buddies2705** [comment]
Ok, will create another thread for the above question. 

But I am still not able to perform sentiment analysis. check this comment..  https://github.com/src-d/hercules/issues/300#issuecomment-516864696

**Comment by vmarkovtsev** [comment]
Considering this as resolved.

**Comment by coinmonks** [comment]
I am still getting `Unsatisfied dependency: [uasts] -> UASTChanges` error ,,mentioned above?

Every other analysis is running fine.

**Comment by vmarkovtsev** [comment]
@coinmonks Does this help? https://github.com/src-d/hercules/issues/300#issuecomment-516820454

**Comment by coinmonks** [comment]
@vmarkovtsev Nope getting this https://github.com/src-d/hercules/issues/300#issuecomment-516850060

**Comment by coinmonks** [comment]
Hey @vmarkovtsev worked , thanks

But when I am running below command

```hercules --sentiment --pb --feature uast ../Pictures/arkcode/php-crypto  | labours -m sentiment -f pb```

I am getting 

```Sentiment stats were not collected. Re-run hercules with --sentiment.```

**Comment by vmarkovtsev** [comment]
Please create a separate issue.
