### ISSUE TITLE
Error parsing message with protobuf

### ISSUE THREAD

**Issue by tkowalczyk** [src-d/hercules#303]
I am trying to run this tools in Docker on Windows and getting the below message. I could not find any similar issue here, thanks in advance

![obraz](https://user-images.githubusercontent.com/1682564/63650581-4cb6c880-c74c-11e9-9867-ed448c531725.png)

**Comment by vmarkovtsev** [comment]
Hi @tkowalczyk you can try writing the file on disk and inspecting it. If all is fine, `cat` it to labours. If the error persists, then docker on windows cannot do pipes, which does not surprise me. In that case, use `labours -i /path/to/file/on/disk`.

**Comment by tkowalczyk** [comment]
While trying with `-i` I am getting following error:

![obraz](https://user-images.githubusercontent.com/1682564/63694031-d1214e00-c815-11e9-8280-c9665815aa19.png)

path is OK, I have created this directory, I have also disabled the firewall, I have no idea how to run it successfully, I really need this great tool

**Comment by vmarkovtsev** [comment]
As you see, it is a `FileNotFoundError`.

**Comment by tkowalczyk** [comment]
yeah you are right but which file? I have created directory `c:\temp\tk_dtm` I have also tested with file like below but I am always getting error.

![obraz](https://user-images.githubusercontent.com/1682564/63702987-5f063480-c828-11e9-85ee-b6525f67b6de.png)

**Comment by vmarkovtsev** [comment]
This is a trivial, 101 Docker usage problem. Sorry, but I don't have the resources for generic support at this time. Try reading what `docker -v` does.

**Comment by vmarkovtsev** [comment]
Please write here if there is still any issue with the project (not with your environment).
