### ISSUE TITLE
Please order `people_sequence` by the person's first commit

### ISSUE THREAD

**Issue by Asday** [src-d/hercules#304]

**Comment by vmarkovtsev** [comment]
Hi @Asday can you please be more specific - I don't remember a thing about my code now.

**Comment by Asday** [comment]
After playing with it a bit, I don't think it does what I wanted.  When I do `labours -m ownership`, it shows some newer contributors underneath older ones, whereas I'd prefer the lowest to the highest in the stack to be in order of appearance.

![image](https://user-images.githubusercontent.com/340276/64948030-1a414c80-d86e-11e9-897b-5b9425f60326.png)

As you can see, with the giant smack of SLOC the purple guy made, it could very well look like the pink guy's work was all removed, and also another pink guy started at the same time.

I thought the order of `people_sequence` determined the stacking order, but I believe I'm wrong.

**Comment by vmarkovtsev** [comment]
ok, got it

**Comment by vmarkovtsev** [comment]
@Asday 10.4.0 has been released: https://pypi.org/project/labours/10.4.0
