### ISSUE TITLE
How to run sentiment analysis?

### ISSUE THREAD

**Issue by akx** [src-d/hercules#316]
This seems related to #300, but I'm not sure how to resolve things still.
Using the prebuilt 10.4.3 / de522fabb931b212f9f007f5b8945126931d3a99 binary.

```
~/Desktop $ ./hercules.darwin_amd64 version
Version: 10
Git:     de522fabb931b212f9f007f5b8945126931d3a99
~/Desktop $ ./hercules.darwin_amd64 --feature uast --first-parent --sentiment --pb ~/build/roi > roi.hercules.uast.pb
(...usage information...)
unknown flag: --sentiment
```

**Comment by vmarkovtsev** [comment]
The prebuilt binaries do not contain Tensorflow-dependent analyses because Tensorflow for Go is a pain in the ass to install (downloading a shady tarball and unpacking it, then writing ldconfigs and running ldconfig) and gives +300MB to the size.

**Comment by akx** [comment]
Haha, fair enough. Thanks for the fast reply! :)

**Comment by vmarkovtsev** [comment]
Actually, `ldconfig` does not even exist in Darwin, so I dunno how to add linker paths there...
