### ISSUE TITLE
v10.6.2 doesn't run on Windows

### ISSUE THREAD

**Issue by fv-ian** [src-d/hercules#335]
Running the command ./hercules.exe help results in no response.   I have reverted back to git release and it runs

```
Version: 10
Git:     a40862d9cbacf05e1866a1718e675964ebd384e3
```

**Comment by vmarkovtsev** [comment]
Hi @fv-ian, `--help` works for me perfectly. I am closing the issue as this is likely a usage problem.

Just in case, you need mingw-w64 installed - namely the following libs:
```
libatomic-1.dll
libgcc_s_seh-1.dll
libgomp-1.dll
libquadmath-0.dll
libssp-0.dll
libstdc++-6.dll
libwinpthread-1.dll
```
