### ISSUE TITLE
Feature request: scattering output of ImportsPerDeveloper by commit

### ISSUE THREAD

**Issue by m09** [src-d/hercules#337]
Thanks @vmarkovtsev for the ImportsPerDeveloper integration of https://github.com/src-d/imports, it works great :fire:

On to the feature request: would it possible to scatter the output by commit? I have to be able to know when the imports were used for the API I'm building, and for that I need to know in which commit they were made. Basically, if I extract all imports from 01/01/2019 to 01/01/2020, I have then to be able to know which imports were made between, say, 04/01/2019 and 09/01/2019.

WDYT?

**Comment by vmarkovtsev** [comment]
All right. Is it enough if I group the imports by day or do you need the commit hashes anyway?

**Comment by m09** [comment]
By day is great!

**Comment by vmarkovtsev** [comment]
https://github.com/src-d/hercules/pull/339

**Comment by vmarkovtsev** [comment]
Please try with v10.7.0

**Comment by m09** [comment]
I tried, output looks fine :100: I'll open a new issue after experimenting with it more if needed.

Thanks @vmarkovtsev for the super-fast feature implementation :rocket:
