### ISSUE TITLE
Feature request: incremental updates

### ISSUE THREAD

**Issue by m09** [src-d/hercules#338]
Following #337, I have another feature request for your consideration!

I'd like to give a commit hash to hercules at which to stop the computation, so that all commits reachable from this commit would not be recomputed (including itself). Only the commits reachable from HEAD to this commit would be computed.

WDYT?

**Comment by vmarkovtsev** [comment]
It is possible to specify the file with the list of commits to be processed via `--commits`. I suggest to do the following:

1. `git log` and filter commit hashes by time as needed. I am sure there are magic options to implement any filtering required.
2. Write them to a file and feed it to `hercules --commits`.

I hope it will work :+1:

**Comment by m09** [comment]
Sounds good :+1:
