### ISSUE TITLE
Feature request: commit timeout / commit size threshold

### ISSUE THREAD

**Issue by m09** [src-d/hercules#342]
Related to #294: I recently hit a big commit (5544 files changed, 9725962 insertions(+), 10094991 deletions(-)), and its processing hangs (or just runs for more than 10 hours). Would it be easy to add a flag to filter those / add a timeout?

**Comment by vmarkovtsev** [comment]
Hey @m09 please check out `--renames-timeout`. Try setting it to 1,000 (1 second). In fact, the default (1 minute) should still be fine.

**Comment by m09** [comment]
Thanks @vmarkovtsev :bowing_man: I'm testing that this morning.

**Comment by m09** [comment]
The repo just reached 1k commits btw :)
