### ISSUE TITLE
Support for Siva as an input format

### ISSUE THREAD

**Issue by bzz** [src-d/hercules#59]
Right now AFAIK hercules does support repository URL or path in local FS to a cache as an input.

It would be great if a path to file in [Siva archive format](https://github.com/src-d/go-siva#%C5%9Biva-format-%E0%A4%B6%E0%A4%BF%E0%A4%B5---) could be supported as well.

**Comment by vmarkovtsev** [comment]
Thank you @bzz - this is exactly my thoughts this weekend.

We need to decide what to do with multiple logical repositories (`HEAD`-s) inside: merge them unconditionally or provide a way to select the branch(es).
