### ISSUE TITLE
Crash on analyzing Microsoft/vscode

### ISSUE THREAD

**Issue by requiel20** [src-d/hercules#60]
I have the repo locally:
> (git-theseus) requiel@requiels-PC ~/gitRepo/vscode $ hercules --burndown --burndown-people .
>  638 / 17076 [==>--------------------------------------------------------] 19m5sfile to schemastore d0c99822ea4ed56bd02ad10877f0b4c9a0539508
> BlobCache failed on commit #639 52953617cbba72333370c22a1cb0d80643ee537c
> panic: file not found
> 
> goroutine 1 [running]:
> main.glob..func3(0x1c3c8c0, 0xc420a769f0, 0x1, 0x3)
> 	/home/travis/gopath/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:202 +0xacc
> github.com/spf13/cobra.(*Command).execute(0x1c3c8c0, 0xc4200100d0, 0x3, 0x3, 0x1c3c8c0, 0xc4200100d0)
> 	/home/travis/gopath/src/github.com/spf13/cobra/command.go:750 +0x2c1
> github.com/spf13/cobra.(*Command).ExecuteC(0x1c3c8c0, 0x26, 0xc42046ab9b, 0x0)
> 	/home/travis/gopath/src/github.com/spf13/cobra/command.go:831 +0x30e
> github.com/spf13/cobra.(*Command).Execute(0x1c3c8c0, 0x0, 0xc4201a7f70)
> 	/home/travis/gopath/src/github.com/spf13/cobra/command.go:784 +0x2b
> main.main()
> 	/home/travis/gopath/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:386 +0x31

**Comment by vmarkovtsev** [comment]
Thanks for your report! Can you please try with `--ignore-missing-submodules`?

**Comment by requiel20** [comment]
That did the job, sorry it was also in the help output
