### ISSUE TITLE
Analyzing repositories with deleted submodules

### ISSUE THREAD

**Issue by schneider-simon** [src-d/hercules#69]
Hello,

first of all I want to thank you for open sourcing this amazing tool. It is a lot of fun to play around with it. 

Unfortunately, I found an issue while running the following command:
```hercules --burndown https://github.com/angular/angular >angular_angular.yaml```

Resulted in:
```
Reading the input... file from tools/rtts-assert 6caafd2561ece8cbfdabbe7357b50ce9192db18c
BlobCache failed on commit #13 61ceed5bf641e3001776332e125a671a06709c9c
panic: file not found

goroutine 1 [running]:
main.glob..func3(0x1c7e980, 0xc420a06b70, 0x1, 0x3)
	/root/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:202 +0xacc
github.com/spf13/cobra.(*Command).execute(0x1c7e980, 0xc4200100d0, 0x3, 0x3, 0x1c7e980, 0xc4200100d0)
	/root/src/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x1c7e980, 0x26, 0xc4201dce91, 0x0)
	/root/src/github.com/spf13/cobra/command.go:843 +0x334
github.com/spf13/cobra.(*Command).Execute(0x1c7e980, 0x0, 0xc42018bf70)
	/root/src/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/root/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:386 +0x31
```

And if we take a look at the commit [https://github.com/angular/angular/commit/61ceed5bf641e3001776332e125a671a06709c9c](https://github.com/angular/angular/commit/61ceed5bf641e3001776332e125a671a06709c9c) we can see that it only removed two submodules.

Is it maybe possible to ignore submodules / commits that remove them?

**Comment by vmarkovtsev** [comment]
Hi @schneider-simon 

Please try `--ignore-missing-submodules` command line option. It should happen because the submodule objects exist in a commit but are removed from `.gitmodules`. Sanity violation I often observe in some large projects. I am considering turning this error into a warning.

**Comment by schneider-simon** [comment]
Adding `--ignore-missing-submodules` worked like a charm. Should have looked in the `--help` before 🙈 Adding a warning sounds like a good idea, since the error message itself can be a bit confusing.
Thank you for the tip.
