### ISSUE TITLE
build error, library not found for tensorflow

### ISSUE THREAD

**Issue by murphygithub** [src-d/hercules#77]
# github.com/tensorflow/tensorflow/tensorflow/go
ld: library not found for -ltensorflow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/macbook/go/bin/hercules] Error 2

**Comment by vmarkovtsev** [comment]
Hi! Tensorflow needs a special installation. Please follow the official manual https://www.tensorflow.org/install/install_go
