### ISSUE TITLE
question: what's the recommended practice to install libtensorflow.so?

### ISSUE THREAD

**Issue by monperrus** [src-d/hercules#80]
I'm getting error `./hercules.linux_amd64: error while loading shared libraries: libtensorflow.so: cannot open shared object file: No such file or directory`

What's the recommended practice to install the right version of libtensorflow.so on Linux/Debian?

Or can `./hercules.linux_amd64` be statically linked?

**Comment by vmarkovtsev** [comment]
Unfortunately, lib tensorflow does not support static linking (I studied that much). So it has to be installed as written in https://www.tensorflow.org/install/install_go

**Comment by monperrus** [comment]
ok thanks.

**Comment by monperrus** [comment]
Thanks to @m09 retrying today, it compiles, it works!
